name: MASQ
dependencies:
  - python=3.*
  - snakemake
  - matplotlib=3.4.*
  - numpy=1.22.0
  - scipy
  - yaml
  - dill
  - editdistance
  - pysam
  - fastqc
  - r-ggplot2
  - r-cowplot
  - primer3
  - blat

channels:
  - conda-forge
  - r
  - bioconda
  - nodefaults
