#!/usr/bin/env bash

declare -a fnames=(
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.000.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.001.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.002.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.003.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.004.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.005.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.006.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.007.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.008.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.009.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.010.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.011.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.012.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.013.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.014.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.015.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.016.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.017.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.018.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.019.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.020.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.021.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.022.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.023.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.024.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.025.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.026.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.027.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.028.png" 
"sample1_cellfree/plots/sample1_cellfree.WGS_varfreqs.029.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.allregions.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_000.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_001.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_002.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_003.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_005.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_006.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_007.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_009.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_010.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_011.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_012.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_013.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_014.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_015.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_016.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_017.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_019.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_021.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_022.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_023.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_024.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_025.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_026.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_028.png" 
"sample1_cellfree/plots/sample1_cellfree.atleastX_reads_per_tag.region_029.png" 
"sample1_cellfree/plots/sample1_cellfree.hamming_distance_SP1_SP2.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.allregions.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_000.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_001.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_002.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_003.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_005.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_006.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_007.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_009.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_010.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_011.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_012.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_013.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_014.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_015.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_016.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_017.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_019.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_021.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_022.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_023.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_024.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_025.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_026.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_028.png" 
"sample1_cellfree/plots/sample1_cellfree.number_reads_per_tag.region_029.png" 
)

for f in ${fnames[@]}; do
    echo "$f: "
    compare -metric mse $f example_outputs_masq/$f null:
    echo
done

echo "done"

