import pickle
import os


ROOT_PATH = "/home/lubo/Work/seq-pipeline/MASQ"


TEST_PCR_PICKLE_FILES = [
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.000.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.000.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.001.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.001.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.002.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.002.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.003.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.003.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.004.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.004.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.005.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.005.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.006.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.006.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.007.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.007.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.008.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.008.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.009.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.009.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.010.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.010.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.011.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.011.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.012.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.012.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.013.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.013.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.014.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.014.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.015.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.015.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.016.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.016.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.017.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.017.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.018.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.018.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.019.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.019.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.020.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.020.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.021.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.021.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.022.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.022.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.023.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.023.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.024.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.024.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.025.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.025.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.026.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.026.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.027.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.027.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.028.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.028.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.029.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.029.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.030.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.030.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.031.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.031.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.032.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.032.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.033.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.033.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.034.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.034.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.035.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.035.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.036.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.036.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.037.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.037.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.038.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.038.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.039.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.039.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.040.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.040.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.041.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.041.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.042.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.042.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.043.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.043.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.044.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.044.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.045.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.045.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.046.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.046.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.047.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.047.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.048.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.048.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.flip_counter.049.pickle", "sample1_blood/pickles/sample1_blood.flip_counter.049.pickle"),

("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.000.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.000.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.001.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.001.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.002.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.002.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.003.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.003.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.004.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.004.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.005.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.005.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.006.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.006.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.007.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.007.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.008.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.008.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.009.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.009.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.010.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.010.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.011.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.011.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.012.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.012.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.013.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.013.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.014.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.014.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.015.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.015.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.016.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.016.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.017.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.017.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.018.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.018.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.019.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.019.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.020.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.020.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.021.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.021.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.022.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.022.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.023.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.023.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.024.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.024.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.025.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.025.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.026.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.026.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.027.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.027.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.028.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.028.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.029.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.029.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.030.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.030.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.031.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.031.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.032.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.032.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.033.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.033.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.034.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.034.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.035.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.035.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.036.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.036.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.037.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.037.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.038.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.038.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.039.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.039.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.040.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.040.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.041.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.041.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.042.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.042.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.043.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.043.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.044.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.044.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.045.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.045.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.046.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.046.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.047.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.047.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.048.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.048.pickle"),
("example_outputs/sample1_blood/pickles/sample1_blood.rolledup.flip_counter.049.pickle", "sample1_blood/pickles/sample1_blood.rolledup.flip_counter.049.pickle"),
]


TEST_PICKLE_FILES: list[tuple[str, str]] = [
("example_outputs/test_example1/pickles/test_example1.flip_counter.000.pickle", "test_example1/pickles/test_example1.flip_counter.000.pickle"),
("example_outputs/test_example1/pickles/test_example1.flip_counter.001.pickle", "test_example1/pickles/test_example1.flip_counter.001.pickle"),
("example_outputs/test_example1/pickles/test_example1.flip_counter.002.pickle", "test_example1/pickles/test_example1.flip_counter.002.pickle"),
("example_outputs/test_example1/pickles/test_example1.flip_counter.003.pickle", "test_example1/pickles/test_example1.flip_counter.003.pickle"),
("example_outputs/test_example1/pickles/test_example1.flip_counter.004.pickle", "test_example1/pickles/test_example1.flip_counter.004.pickle"),
("example_outputs/test_example1/pickles/test_example1.flip_counter.005.pickle", "test_example1/pickles/test_example1.flip_counter.005.pickle"),
("example_outputs/test_example1/pickles/test_example1.flip_counter.006.pickle", "test_example1/pickles/test_example1.flip_counter.006.pickle"),
("example_outputs/test_example1/pickles/test_example1.flip_counter.007.pickle", "test_example1/pickles/test_example1.flip_counter.007.pickle"),
("example_outputs/test_example1/pickles/test_example1.flip_counter.008.pickle", "test_example1/pickles/test_example1.flip_counter.008.pickle"),
("example_outputs/test_example1/pickles/test_example1.flip_counter.009.pickle", "test_example1/pickles/test_example1.flip_counter.009.pickle"),
("example_outputs/test_example1/pickles/test_example1.flip_counter.010.pickle", "test_example1/pickles/test_example1.flip_counter.010.pickle"),
("example_outputs/test_example1/pickles/test_example1.flip_counter.011.pickle", "test_example1/pickles/test_example1.flip_counter.011.pickle"),
("example_outputs/test_example1/pickles/test_example1.flip_counter.012.pickle", "test_example1/pickles/test_example1.flip_counter.012.pickle"),
("example_outputs/test_example1/pickles/test_example1.flip_counter.013.pickle", "test_example1/pickles/test_example1.flip_counter.013.pickle"),
("example_outputs/test_example1/pickles/test_example1.flip_counter.014.pickle", "test_example1/pickles/test_example1.flip_counter.014.pickle"),
("example_outputs/test_example1/pickles/test_example1.flip_counter.015.pickle", "test_example1/pickles/test_example1.flip_counter.015.pickle"),
("example_outputs/test_example1/pickles/test_example1.flip_counter.016.pickle", "test_example1/pickles/test_example1.flip_counter.016.pickle"),
("example_outputs/test_example1/pickles/test_example1.flip_counter.017.pickle", "test_example1/pickles/test_example1.flip_counter.017.pickle"),
("example_outputs/test_example1/pickles/test_example1.flip_counter.018.pickle", "test_example1/pickles/test_example1.flip_counter.018.pickle"),
("example_outputs/test_example1/pickles/test_example1.flip_counter.019.pickle", "test_example1/pickles/test_example1.flip_counter.019.pickle"),

("example_outputs/test_example1/pickles/test_example1.rolledup.flip_counter.000.pickle", "test_example1/pickles/test_example1.rolledup.flip_counter.000.pickle"),
("example_outputs/test_example1/pickles/test_example1.rolledup.flip_counter.001.pickle", "test_example1/pickles/test_example1.rolledup.flip_counter.001.pickle"),
("example_outputs/test_example1/pickles/test_example1.rolledup.flip_counter.002.pickle", "test_example1/pickles/test_example1.rolledup.flip_counter.002.pickle"),
("example_outputs/test_example1/pickles/test_example1.rolledup.flip_counter.003.pickle", "test_example1/pickles/test_example1.rolledup.flip_counter.003.pickle"),
("example_outputs/test_example1/pickles/test_example1.rolledup.flip_counter.004.pickle", "test_example1/pickles/test_example1.rolledup.flip_counter.004.pickle"),
("example_outputs/test_example1/pickles/test_example1.rolledup.flip_counter.005.pickle", "test_example1/pickles/test_example1.rolledup.flip_counter.005.pickle"),
("example_outputs/test_example1/pickles/test_example1.rolledup.flip_counter.006.pickle", "test_example1/pickles/test_example1.rolledup.flip_counter.006.pickle"),
("example_outputs/test_example1/pickles/test_example1.rolledup.flip_counter.007.pickle", "test_example1/pickles/test_example1.rolledup.flip_counter.007.pickle"),
("example_outputs/test_example1/pickles/test_example1.rolledup.flip_counter.008.pickle", "test_example1/pickles/test_example1.rolledup.flip_counter.008.pickle"),
("example_outputs/test_example1/pickles/test_example1.rolledup.flip_counter.009.pickle", "test_example1/pickles/test_example1.rolledup.flip_counter.009.pickle"),
("example_outputs/test_example1/pickles/test_example1.rolledup.flip_counter.010.pickle", "test_example1/pickles/test_example1.rolledup.flip_counter.010.pickle"),
("example_outputs/test_example1/pickles/test_example1.rolledup.flip_counter.011.pickle", "test_example1/pickles/test_example1.rolledup.flip_counter.011.pickle"),
("example_outputs/test_example1/pickles/test_example1.rolledup.flip_counter.012.pickle", "test_example1/pickles/test_example1.rolledup.flip_counter.012.pickle"),
("example_outputs/test_example1/pickles/test_example1.rolledup.flip_counter.013.pickle", "test_example1/pickles/test_example1.rolledup.flip_counter.013.pickle"),
("example_outputs/test_example1/pickles/test_example1.rolledup.flip_counter.014.pickle", "test_example1/pickles/test_example1.rolledup.flip_counter.014.pickle"),
("example_outputs/test_example1/pickles/test_example1.rolledup.flip_counter.015.pickle", "test_example1/pickles/test_example1.rolledup.flip_counter.015.pickle"),
("example_outputs/test_example1/pickles/test_example1.rolledup.flip_counter.016.pickle", "test_example1/pickles/test_example1.rolledup.flip_counter.016.pickle"),
("example_outputs/test_example1/pickles/test_example1.rolledup.flip_counter.017.pickle", "test_example1/pickles/test_example1.rolledup.flip_counter.017.pickle"),
("example_outputs/test_example1/pickles/test_example1.rolledup.flip_counter.018.pickle", "test_example1/pickles/test_example1.rolledup.flip_counter.018.pickle"),
("example_outputs/test_example1/pickles/test_example1.rolledup.flip_counter.019.pickle", "test_example1/pickles/test_example1.rolledup.flip_counter.019.pickle"),
]

infiles = TEST_PCR_PICKLE_FILES
infiles = TEST_PICKLE_FILES

for old, new in infiles:
    with open(os.path.join(ROOT_PATH, old), "rb") as infile:
        old_data = pickle.load(infile)
    with open(os.path.join(ROOT_PATH, new), "rb") as infile:
        new_data = pickle.load(infile)

    assert old_data == new_data
